### ISSUE TITLE
Call/SMS Log saved in a different Deal Card

### ISSUE THREAD

**Issue by TNDevSupport** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#44]
Hi,

I'm currently using v2.6.1 and noticed that Call/SMS Log is being saved in a different Deal Card. Also, some of our users don't use RingCentral but their Deal Card is also affected. How can I resolve this once and for all?

**Comment by zxdong262** [comment]
@TNDevSupport 

Can you check if anyone in your company using old release older than 2.6.0? If so it may happen due to known bug, just make sure everyone use latest release, it will not happen again.

If no one in your team use old 2.5 or older release, then it is a some new situation I do not know. Then can we have a meeting to check it? You can send me your available time/timezone to drake.zhao@ringcentral.com (please exlucde 1:00AM - 7:00AM UTC+8 timezone)
